export const icons: { [key: string]: string } = {
  pdf: 'pi pi-file-pdf',
  doc: 'pi pi-file-word',
  docx: 'pi pi-file-word',
  csv: 'pi pi-file-excel',
  xls: 'pi pi-file-excel',
  xlsx: 'pi pi-file-excel',
  ppt: 'pi pi-file-powerpoint',
  pptx: 'pi pi-file-powerpoint',
  txt: 'pi pi-file',
  zip: 'pi pi-file-archive',
  default: 'pi pi-file',
  add: 'pi pi-plus',
  edit: 'pi pi-pencil',
  delete: 'pi pi-trash',
  changePassword: 'pi pi-key',
  editUser: 'pi pi-user-edit',
  exportFile: 'fa-solid fa-file-export',
  importFile: 'fa-solid fa-file-import',
  activate: 'fa-solid fa-toggle-on',
  deactivate: 'fa-solid fa-toggle-off',
  company: 'fa-solid fa-landmark',
  fgne: 'fa-solid fa-people-roof',
};
