import {
  LucidePlus,
  LucidePencil,
  LucideTrash2,
  LucideEye,
  LucideKey,
  LucideUserPen,
  LucideDownload,
  LucideCloudUpload,
  LucideToggleRight,
  LucideToggleLeft,
  LucideLandmark,
  LucideUsers,
  LucideFileText,
  LucideArchive,
  LucideFile,
  LucideFileSpreadsheet,
  LucidePresentation,
  LucideSettings,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideHome,
  LucideBarChart3,
  LucideLineChart,
  LucideChevronUp,
  LucideLayoutGrid,
  LucideImages,
  LucideNewspaper,
  LucideBuilding,
  LucideArchiveX,
  LucideBadge,
  LucidePenSquare,
  LucideShoppingCart,
  LucideFileBox,
  LucideBook,
  LucideHeadset,
  LucideInfo,
  LucideUserCog,
  LucideBot,
  LucideCpu,
  LucideSliders,
  LucideCircle,
  LucideWarehouse,
  LucideUserCheck,
  LucideList,
  LucideBookOpenCheck,
  LucideSave,
  LucideDatabaseBackup,
  LucideLogOut,
  LucideMenu,
  LucideX,
  LucideUserRoundX,
  LucideUserPlus,
  LucideGripHorizontal,
  LucideLoaderCircle,
  LucideEyeOff,
  LucideRefreshCw,
  LucideFilter,
  LucideArrowUpDown,
  LucideArrowUp,
  LucideArrowDown,
  LucideTriangleAlert,
  LucideUpload,
  LucideMinimize2,
  LucideMaximize2,
  LucideCircleCheck,
  LucideCircleX,
} from '@lucide/angular';

// Nombres semánticos → kebab (lo que usan tus listados)
export const icons: Record<string, string> = {
  // archivos
  pdf: 'file-text',
  doc: 'file-text',
  docx: 'file-text',
  csv: 'file-spreadsheet',
  xls: 'file-spreadsheet',
  xlsx: 'file-spreadsheet',
  ppt: 'presentation',
  pptx: 'presentation',
  txt: 'file',
  zip: 'archive',
  default: 'file',
  // acciones CRUD
  add: 'plus',
  edit: 'pencil',
  delete: 'trash-2',
  changePassword: 'key',
  editUser: 'user-pen',
  view: 'eye',
  exportFile: 'download',
  importFile: 'cloud-upload',
  activate: 'toggle-right',
  deactivate: 'toggle-left',
  // negocio
  company: 'landmark',
  fgne: 'users',
  // navegación / UI
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  circle: 'circle',
  // iconos del sidebar
  home: 'home',
  settings: 'settings',
  'bar-chart': 'bar-chart-3',
  'line-chart': 'line-chart',
  'chevron-up': 'chevron-up',
  'layout-grid': 'layout-grid',
  images: 'images',
  newspaper: 'newspaper',
  building: 'building',
  'archive-x': 'archive-x',
  badge: 'badge',
  'pen-square': 'pen-square',
  'shopping-cart': 'shopping-cart',
  postcard: 'file-box',
  book: 'book',
  headset: 'headset',
  info: 'info',
  'user-cog': 'user-cog',
  robot: 'bot',
  cpu: 'cpu',
  sliders: 'sliders',
  warehouse: 'warehouse',
  'user-star': 'user-star',
  list: 'list',
  'book-open-check': 'book-open-check',
  // iconos del navbar
  save: 'save',
  'database-backup': 'database-backup',
  'arrow-left-from-line': 'log-out',
  'log-out': 'log-out',
  menu: 'menu',
  x: 'x',
  'user-round-exclamation': 'user-round-x',
  'user-plus': 'user-plus',
  'grip-horizontal': 'grip-horizontal',
  users: 'users',
  bot: 'bot',
  // iconos del login
  'loader-circle': 'loader-circle',
  eye: 'eye',
  'eye-off': 'eye-off',
  // iconos de la tabla
  'refresh-cw': 'refresh-cw',
  filter: 'filter',
  'arrow-up-down': 'arrow-up-down',
  'arrow-up': 'arrow-up',
  'arrow-down': 'arrow-down',
  // iconos de componentes shared
  'triangle-alert': 'triangle-alert',
  upload: 'upload',
  'minimize-2': 'minimize-2',
  'maximize-2': 'maximize-2',
  'circle-check': 'circle-check',
  'circle-x': 'circle-x',
};

// Kebab → componente Lucide (solo lo usa la tabla internamente)
export const lucideIconMap: Record<string, any> = {
  plus: LucidePlus,
  pencil: LucidePencil,
  'trash-2': LucideTrash2,
  eye: LucideEye,
  key: LucideKey,
  'user-pen': LucideUserPen,
  download: LucideDownload,
  'cloud-upload': LucideCloudUpload,
  'toggle-right': LucideToggleRight,
  'toggle-left': LucideToggleLeft,
  landmark: LucideLandmark,
  users: LucideUsers,
  'file-text': LucideFileText,
  'file-spreadsheet': LucideFileSpreadsheet,
  presentation: LucidePresentation,
  file: LucideFile,
  archive: LucideArchive,
  // iconos del sidebar
  home: LucideHome,
  settings: LucideSettings,
  'bar-chart-3': LucideBarChart3,
  'line-chart': LucideLineChart,
  'chevron-up': LucideChevronUp,
  'layout-grid': LucideLayoutGrid,
  images: LucideImages,
  newspaper: LucideNewspaper,
  building: LucideBuilding,
  'archive-x': LucideArchiveX,
  badge: LucideBadge,
  'pen-square': LucidePenSquare,
  'shopping-cart': LucideShoppingCart,
  'file-box': LucideFileBox,
  book: LucideBook,
  headset: LucideHeadset,
  info: LucideInfo,
  'user-cog': LucideUserCog,
  bot: LucideBot,
  cpu: LucideCpu,
  sliders: LucideSliders,
  'chevron-down': LucideChevronDown,
  'chevron-left': LucideChevronLeft,
  'chevron-right': LucideChevronRight,
  circle: LucideCircle,
  warehouse: LucideWarehouse,
  'user-star': LucideUserCheck,
  list: LucideList,
  'book-open-check': LucideBookOpenCheck,
  // iconos del navbar
  save: LucideSave,
  'database-backup': LucideDatabaseBackup,
  'log-out': LucideLogOut,
  menu: LucideMenu,
  x: LucideX,
  'user-round-x': LucideUserRoundX,
  'user-plus': LucideUserPlus,
  'grip-horizontal': LucideGripHorizontal,
  // iconos del login
  'loader-circle': LucideLoaderCircle,
  'eye-off': LucideEyeOff,
  // iconos de la tabla
  'refresh-cw': LucideRefreshCw,
  filter: LucideFilter,
  'arrow-up-down': LucideArrowUpDown,
  'arrow-up': LucideArrowUp,
  'arrow-down': LucideArrowDown,
  // iconos de componentes shared
  'triangle-alert': LucideTriangleAlert,
  upload: LucideUpload,
  'minimize-2': LucideMinimize2,
  'maximize-2': LucideMaximize2,
  'circle-check': LucideCircleCheck,
  'circle-x': LucideCircleX,
};

/** Resuelve un nombre semántico o kebab al componente Lucide */
export function getLucideIcon(name: string): any {
  // Primero intenta kebab directo, luego resuelve desde icons{}
  return lucideIconMap[name] ?? lucideIconMap[icons[name]] ?? LucidePlus;
}
